apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mydb
  name: mydb
spec:
  ports:
  - 
    port: 80
    protocol: TCP
    targetPort: 9377
  type: ClusterIP
status:
  loadBalancer: {}
