apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mysql-pod
  name: sql01
  namespace: dev
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql-pod
status:
  loadBalancer: {}
