apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-pod
  annotations:
    buildversion: "1.3"
    developer: jahidularafat
    email: jahidul.arafat@oracle.com

    
  namespace: dev
  name: mysql-pod
spec:
  serviceAccountName: dashboard-sa
  containers:
  - image: mysql:5.6.23
    name: mysql-pod
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password123
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
