apiVersion: v1
kind: Pod
metadata:
  labels:
    run: random-number-generator
  name: random-number-generator
spec:
  containers:
  - image: alpine
    name: random-container
    command:
      - "/bin/sh"
      - "-c"
    args:
      - "shuf -i 0-100 -n 1 >> /opt/number.out;"
    resources: {}
    volumeMounts:
      - mountPath: /opt
        name: data-volume
  volumes:
    - name: data-volume
      hostPath:
        path: /data
        type: Directory
