apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: simple-job
spec:
  completions: 12
  parallelism: 3
  backoffLimit: 6
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: kodekloud/random-error
        name: simple-job
        resources: {}
      restartPolicy: Never
status: {}
