apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: simple-cronjob
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: simple-cronjob
    spec:
      completions: 12
      parallelism: 3
      backoffLimit: 6
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: ubuntu
            name: simple-cronjob
            command: ["expr", "2","+","3"]
            resources: {}
          restartPolicy: OnFailure
  schedule: 0 16 * * *
status: {}
