apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: task-pv-pod
  name: task-pv-pod
spec:
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: task-pv-claim
  containers:
  - image: nginx
    name: task-pv-pod
    ports:
      - name: http-server
        containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: task-pv-storage
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
