apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu-sleeper
  name: ubuntu-sleeper
spec:
  securityContext:
   runAsUser: 0
  containers:
  - image: ubuntu
    name: ubuntu-sleeper
    command: 
     - "sleep"
     - "3600"
    securityContext:
     runAsUser: 1000
     capabilities:
      add: ["MAC_ADMIN"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
