apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
  labels:
    name: ubuntu-sleeper
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: ubuntu-sleeper-container
    image: ubuntu
    command:
      - "sleep"
      - "3600"
    ports:
      - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /api/ready
        port: 8080
      periodSeconds: 5
      initialDelaySeconds: 10
      failureThreshold: 8

    livenessProbe:
      httpGet:
        path: /api/healthy
        port: 8080
      periodSeconds: 5
      initialDelaySeconds: 10
      failureThresholds: 8
      
    securityContext:
      runAsUser: root
      capabilities:
        add:
          - "MAC_ADMIN"
          - "SYS_TIME"
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ['sh','-c','git clone <some-reposiorty-used-by-the-main-application>']
    - name: init-mydb
      image: busybox:1.28
      command: ['sh', '-c', 'until nslookup mydb; do echo waiting for mydb; sleep 2; done;']
