apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webapp-mysql-pod
  name: webapp-mysql-pod
  namespace: dev
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    name: webapp-mysql-pod
    envFrom:
      - secretRef:
          name: db-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
