apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: sample-webapp-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
    type: frontend
  type: NodePort
status:
  loadBalancer: {}
