apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: dev
  name: dev-quota
spec:
  hard:
    requests.cpu: "1"
    limits.cpu: "10"
    requests.memory: 1G
    limits.memory: 10G
    persistentvolumeclaims: "10"
    pods: "10"
    replicationcontrollers: "2"
    resourcequotas: "1"
    secrets: "5"
    services: "3"

