apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
  labels:
    name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/pv-cluster/pv-vol1
  

