apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: elastic-search
  name: elastic-search
  namespace: elastic-stack
spec:
  containers:
  - image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    name: elastic-search
    command:
    - "sleep"
    - "1000"
    ports:
    - containerPort: 9300
    - containerPort: 9200
    resources: {}
    env:
    - name: discovery.type
      value: single-node
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
