apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kibana
  name: kibana
  namespace: elastic-stack
spec:
  containers:
  - image: kibana:8.6.0
    name: kibana
    env:
    - name: ELASTICSEARCH_URL
      value: http://elasticsearch:9200
    command:
    - "sleep"
    - "1000"
    ports:
    - containerPort: 5601
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
