apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: math-add-job
  namespace: dev
spec:
  completions: 3
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: ubuntu
        name: math-add-job-container
        resources: {}
        command:
          - "expr"
          - '3'
          - '+'
          - '2'
      restartPolicy: Never
status: {}
