apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: liveness
  name: liveness
spec:
  containers:
  - image: registry.k8s.io/liveness
    name: liveness
    args:
    - /server
    livenessProbe:
     httpGet:
       path: /healthz
       port: 8080
       httpHeaders:
       - name: Custom-Header
         value: Awesome
     initialDelaySeconds: 3
     periodSeconds: 3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
