apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: startup-probe
  name: startup-probe
spec:
  containers:
  - image: registry.k8s.io/goproxy:0.1
    name: startup-probe
    ports:
    - name: liveness-port 
      containerPort: 8080
      hostPort: 8080
    startupProbe:
     httpGet:
      path: /healthz
      port: liveness-port
     periodSeconds: 10
     failureThreshold: 1
    livenessProbe:
     httpGet:
      path: /healthz
      port: liveness-port
     periodSeconds: 10
     failureThreshold: 30
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
