apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu-sleeper
  name: ubuntu-sleeper
  namespace: stage
spec:
  containers:
  - image: ubuntu
    name: ubuntu-sleeper
    command: ["sleep"]
    args: ["10"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
